# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\x07storage\".\n\x0cStoreRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"1\n\rStoreResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\nGetRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\"=\n\x0bGetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0f\n\x07message\x18\x03 \x01(\t\"!\n\rDeleteRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\"\n\rSpaceResponse\x12\x11\n\tavailable\x18\x01 \x01(\x03\x32\xfe\x01\n\x0bStorageNode\x12;\n\nStoreBlock\x12\x15.storage.StoreRequest\x1a\x16.storage.StoreResponse\x12\x35\n\x08GetBlock\x12\x13.storage.GetRequest\x1a\x14.storage.GetResponse\x12>\n\x0b\x44\x65leteBlock\x12\x16.storage.DeleteRequest\x1a\x17.storage.DeleteResponse\x12;\n\x11GetAvailableSpace\x12\x0e.storage.Empty\x1a\x16.storage.SpaceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOREREQUEST']._serialized_start=26
  _globals['_STOREREQUEST']._serialized_end=72
  _globals['_STORERESPONSE']._serialized_start=74
  _globals['_STORERESPONSE']._serialized_end=123
  _globals['_GETREQUEST']._serialized_start=125
  _globals['_GETREQUEST']._serialized_end=155
  _globals['_GETRESPONSE']._serialized_start=157
  _globals['_GETRESPONSE']._serialized_end=218
  _globals['_DELETEREQUEST']._serialized_start=220
  _globals['_DELETEREQUEST']._serialized_end=253
  _globals['_DELETERESPONSE']._serialized_start=255
  _globals['_DELETERESPONSE']._serialized_end=305
  _globals['_EMPTY']._serialized_start=307
  _globals['_EMPTY']._serialized_end=314
  _globals['_SPACERESPONSE']._serialized_start=316
  _globals['_SPACERESPONSE']._serialized_end=350
  _globals['_STORAGENODE']._serialized_start=353
  _globals['_STORAGENODE']._serialized_end=607
# @@protoc_insertion_point(module_scope)
